apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-gateway-config
data:
  SPRING_DATASOURCE_URL: 'jdbc:mysql://payment-gateway-mysql:3306/payment_gateway'
  SPRING_DATASOURCE_USERNAME: 'root'
  SPRING_DATASOURCE_PASSWORD: 'password'


---

# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: payment-gateway:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: payment-gateway-config

---

# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
spec:
  type: LoadBalancer
  selector:
    app: payment-gateway
  ports:
    - port: 8081
      targetPort: 8081
